application: wf-ghconsole
version: 3 
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.application  
  login: required
# auth_fail_action: unauthorized

env_variables:
  CLIENT_ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxx
  ORG: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ACCESS_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxx
  SESSION_SECRET: xxxxxxxxxxxxxxxxxxxxxxxx
