application: wf-ghconsole
version: 3 
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /get-auth-token
  script: githubauth.application

- url: /get-access-token/.*
  script: githubauth.application

- url: /log-user-in
  script: githubauth.application

- url: /.*
  script: main.application  
  login: required
# secure: always
# auth_fail_action: unauthorized

env_variables:
  CLIENT_ID:  
  CLIENT_SECRET:  
  ORG:  
  ACCESS_TOKEN: 
  SESSION_SECRET: 
