application: wf-ghconsole
version: 3 
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /app
  script: main.app

- url: /create-repo
  script: repo.app

- url: /get-data
  script: repo.app

- url: /add-team
  script: teams.app

- url: /remove-team
  script: teams.app

- url: /edit-team
  script: teams.app

- url: /change-team
  script: teams.app

- url: /.*
  script: auth.app  
  # login: required
  # auth_fail_action: unauthorized
  # secure: always

env_variables:
  ORG: wf-console-test # Org name goes here
  ADMIN_EMAIL: some@thing.com # Daily digest of logs will be sent here 


