application: wf-ghconsole
version: 3 
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /app
  script: main.app

- url: /.*repo
  script: repo.app

- url: /.*team
  script: teams.app

- url: /.*logs
  script: logs.app

- url: /.*
  script: auth.app  
  # login: required
  # auth_fail_action: unauthorized
  # secure: always

env_variables:
  ORG: # Org name goes here
  ADMIN_EMAIL: # Daily digest of logs will be sent here 
